site_name: IM-POWER
site_url: https://btagliafierro.github.io/impower/
site_author: Bonaventura Tagliafierro

nav:
  - Home: 'pages/index.md'
  - Background: 'pages/background.md'
  - Overview: 'pages/overview.md'
  - Implementation: 'pages/implementation.md'
  - Software: 'pages/code.md'
  - Outcome: 'pages/outcome.md'
  - Conferences & Papers: 'pages/outcome_conferences.md'
  - Contact: 'pages/contact.md'

theme:
  name: material
  language: en
  custom_dir: overrides/
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  font:
    text: Source Serif 4
    code: JetBrains Mono
  icon:
    annotation: material/arrow-right-circle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

copyright: >
  Funded by the European Union under the Horizon Europe Marie Skłodowska-Curie Actions,
  grant agreement No 101109440 (IM-POWER). Views and opinions expressed are those of the
  author only and do not necessarily reflect those of the European Union or the European
  Research Executive Agency. Neither the European Union nor the granting authority can be
  held responsible for them. &copy; 2026 IM-POWER Project

extra:
  homepage: https://btagliafierro.github.io/impower/
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:bonaventura.tagliafierro@angstrom.uu.se
      name: Contact
    - icon: fontawesome/brands/github
      link: https://github.com/btagliafierro
      name: GitHub

markdown_extensions:
  - tables
  - smarty
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      toc_depth: 3
      permalink: true
      separator: "_"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js